# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  new: /null
rss: /atom.xml

home:
  style: default           # default, detail

favicon:                  # Path to the custom favicon (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: false            # Display banner
  url: /assets/banner.png
  position: center         # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true         # Display banner on all pages

# Appearence
hue: 285                   # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
      - archive
      - recent_posts

# Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5

# Personal info
avatar: ./shiro1.png
author: Asukai
subtitle: This is the subtitle
links:
  - name: Gitee
    icon: fa fa-user     # Find icon codes at https://fontawesome.com/search
    url: https://gitee.com/Cn_asukai
  - name: Steam
    icon: fa-brands fa-steam
    url: https://steamcommunity.com/id/Cn_Asukai/
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/Cn-Asukai

comment:
  valine:
    enable: false
    appId: 
    appKey: 
